"""Writes reads.sam: 1500 records (3 batches of 512 and change), deterministic.
- CB:Z cycles through 7 barcodes; every 10th record has no CB (null key).
- every 13th record is unmapped (flag 4), every 3rd is reverse (flag 16).
- read i starts at 1 + i % 20 and is 12 bases, with C->T at non-CG Cs,
  and the CG C converted on odd i (so calls vary)."""
ref = open("ref.fa").read().split("\n")[1]
out = ["@HD\tVN:1.6\tSO:unsorted", "@SQ\tSN:chr1\tLN:%d" % len(ref),
       "@CO\tGenerated by make_reads.py; see its docstring."]
for i in range(1500):
    start = i % 20
    seg = list(ref[start:start + 12])
    for j, b in enumerate(seg):
        p = start + j
        if b == "C" and not (ref[p + 1:p + 2] == "G" and i % 2 == 0):
            seg[j] = "T"
    flag = 4 if i % 13 == 0 else (16 if i % 3 == 0 else 0)
    tags = [] if i % 10 == 0 else ["CB:Z:BC%d" % (i % 7)]
    if flag == 4:
        f = ["r%04d" % i, "4", "*", "0", "0", "*", "*", "0", "0", "".join(seg), "I" * 12]
    else:
        f = ["r%04d" % i, str(flag), "chr1", str(start + 1), str(i % 61), "12M", "*", "0", "0", "".join(seg), "I" * 12]
    out.append("\t".join(f + tags))
open("reads.sam", "w").write("\n".join(out) + "\n")
